export const currencies = [
  { name: 'XAF', symbol: 'FCFA', position: 'after', rate: 1 },
  { name: 'XOF', symbol: 'FCFA', position: 'after', rate: 1 },
  { name: 'NGN', symbol: '₦', position: 'before', rate: 0.92 },
  { name: 'GHS', symbol: 'GH₵', position: 'before', rate: 0.014 },
  { name: 'ZAR', symbol: 'R', position: 'before', rate: 0.03 },
  { name: 'EGP', symbol: '£', position: 'before', rate: 0.05 },
  { name: 'KES', symbol: 'KSh', position: 'before', rate: 0.17 },
  { name: 'MAD', symbol: 'د.م', position: 'after', rate: 0.018 },
  { name: 'TND', symbol: 'د.ت', position: 'after', rate: 0.0048 },

  { name: 'USD', symbol: '$', position: 'before', rate: 0.0016 },
  { name: 'CAD', symbol: '$', position: 'before', rate: 0.0022 },
  { name: 'MXN', symbol: '$', position: 'before', rate: 0.027 },
  { name: 'BRL', symbol: 'R$', position: 'before', rate: 0.008 },
  { name: 'ARS', symbol: '$', position: 'before', rate: 0.56 },
  { name: 'CLP', symbol: '$', position: 'before', rate: 1.5 },
  { name: 'COP', symbol: '$', position: 'before', rate: 6.3 },

  { name: 'EUR', symbol: '€', position: 'after', rate: 0.0015 },
  { name: 'GBP', symbol: '£', position: 'before', rate: 0.0013 },
  { name: 'CHF', symbol: 'CHF', position: 'after', rate: 0.0015 },
  { name: 'SEK', symbol: 'kr', position: 'after', rate: 0.017 },
  { name: 'NOK', symbol: 'kr', position: 'after', rate: 0.017 },
  { name: 'DKK', symbol: 'kr', position: 'after', rate: 0.011 },
  { name: 'PLN', symbol: 'zł', position: 'after', rate: 0.0066 },
  { name: 'CZK', symbol: 'Kč', position: 'after', rate: 0.038 },
  { name: 'HUF', symbol: 'Ft', position: 'after', rate: 0.56 },
  { name: 'RON', symbol: 'lei', position: 'after', rate: 0.0074 },

  { name: 'AED', symbol: 'د.إ', position: 'after', rate: 0.0059 },
  { name: 'SAR', symbol: '﷼', position: 'after', rate: 0.006 },
  { name: 'QAR', symbol: '﷼', position: 'after', rate: 0.0058 },
  { name: 'ILS', symbol: '₪', position: 'before', rate: 0.0059 },
  { name: 'TRY', symbol: '₺', position: 'before', rate: 0.05 },

  { name: 'CNY', symbol: '¥', position: 'before', rate: 0.011 },
  { name: 'JPY', symbol: '¥', position: 'before', rate: 0.24 },
  { name: 'KRW', symbol: '₩', position: 'before', rate: 2.1 },
  { name: 'INR', symbol: '₹', position: 'before', rate: 0.13 },
  { name: 'IDR', symbol: 'Rp', position: 'before', rate: 25 },
  { name: 'MYR', symbol: 'RM', position: 'before', rate: 0.0075 },
  { name: 'THB', symbol: '฿', position: 'before', rate: 0.056 },
  { name: 'VND', symbol: '₫', position: 'after', rate: 38 },
  { name: 'PHP', symbol: '₱', position: 'before', rate: 0.088 },
  { name: 'SGD', symbol: '$', position: 'before', rate: 0.0022 },
  { name: 'HKD', symbol: '$', position: 'before', rate: 0.012 },

  { name: 'AUD', symbol: '$', position: 'before', rate: 0.0024 },
  { name: 'NZD', symbol: '$', position: 'before', rate: 0.0026 },

  { name: 'RUB', symbol: '₽', position: 'after', rate: 0.15 },
  { name: 'UAH', symbol: '₴', position: 'after', rate: 0.06 },
  { name: 'BDT', symbol: '৳', position: 'before', rate: 0.18 },
  { name: 'PKR', symbol: '₨', position: 'before', rate: 0.45 },
  { name: 'LKR', symbol: 'Rs', position: 'before', rate: 0.5 },
  { name: 'NPR', symbol: '₨', position: 'before', rate: 0.21 },
  { name: 'DZD', symbol: 'دج', position: 'after', rate: 0.22 },
  { name: 'ETB', symbol: 'Br', position: 'before', rate: 0.09 },
  { name: 'TZS', symbol: 'Sh', position: 'before', rate: 4.1 },
  { name: 'UGX', symbol: 'USh', position: 'before', rate: 6.1 },
] as const

export type Currency = typeof currencies[number];
export type CurrencyName = Currency['name'];
